// <auto-generated />
using System;
using Clinical.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clinical.Infrastructure.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    partial class ClinicalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinical.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PredictionRunId")
                        .HasColumnType("uuid");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PredictionRunId");

                    b.HasIndex("EncounterId", "Status", "CreatedAtUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Clinical.Domain.Entities.FeatureRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FeatureVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid[]>("InputEventIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("PipelineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProcessedEvents")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("PipelineName", "EncounterId", "WindowEndUtc");

                    b.ToTable("feature_runs", (string)null);
                });

            modelBuilder.Entity("Clinical.Domain.Entities.PipelineWatermark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("LastProcessedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("PipelineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PipelineName")
                        .IsUnique();

                    b.ToTable("pipeline_watermarks", (string)null);
                });

            modelBuilder.Entity("Clinical.Domain.Entities.PredictionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FeatureRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("HorizonHours")
                        .HasColumnType("integer");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<string>("SurvivalSummaryJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("FeatureRunId", "CreatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("prediction_runs", (string)null);
                });

            modelBuilder.Entity("Clinical.Domain.Entities.RawEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("EncounterId", "OccurredAtUtc");

                    b.HasIndex("PatientId", "OccurredAtUtc");

                    b.ToTable("raw_events", (string)null);
                });

            modelBuilder.Entity("Clinical.Domain.Entities.Alert", b =>
                {
                    b.HasOne("Clinical.Domain.Entities.PredictionRun", "PredictionRun")
                        .WithMany()
                        .HasForeignKey("PredictionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PredictionRun");
                });

            modelBuilder.Entity("Clinical.Domain.Entities.PredictionRun", b =>
                {
                    b.HasOne("Clinical.Domain.Entities.FeatureRun", "FeatureRun")
                        .WithMany()
                        .HasForeignKey("FeatureRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureRun");
                });
#pragma warning restore 612, 618
        }
    }
}
